### PR TITLE
add app that generates wifi mac (works) and bt (not jet) and init script

### PR DESCRIPTION
**Pull request by bademux**
Change-Id: Idcca0dd45f3019157b196c0c696afa9d6417e41e

### CODE REVIEW

**Comment by mifl** [comment]
Thanks for your contribution.

**Comment by bademux** [comment]
Welcome, 
thanks go to @jied83 and @stevotdo as well as credits
Thanks.

**Comment by stevotdo** [comment]
hwaddrs runs to early

Delete the added lines in init.presto.rc 

and add this at the very bottom of the file.

"## Read Wifi Mac Address
on property:wifi.interface=wlan0
   exec /system/bin/hwaddrs" 

minus the parenthesis

**Comment by mifl** [comment]
Ok.
We leave the repo free for other exchanges. @stevotdo: we approve this request, and later you include this correction, directly in the repo.

**Comment by stevotdo** [comment]
Ok

**Pull request merged**
