### PR TITLE
CM Power Hal; disable PrestoParts; Time Daemon fixes(to fix time resets)

### PR DESCRIPTION
**Pull request by jied83**
Time Daemon fixes(to fix time resets)
also check:
https://github.com/PantechDevTeam/android_device_pantech_msm8660-common/pull/11
https://github.com/PantechDevTeam/android_vendor_pantech_presto/pull/1

### CODE REVIEW

**Comment by mifl** [comment]
cm powerhal already defined: 
https://github.com/PantechDevTeam/android_device_pantech_msm8x60-common/blob/cm-11.0/BoardConfigCommon.mk#L68

**Comment by jied83** [comment]
this is old declaration, now we need to specify what variant of power hal to use

https://github.com/CyanogenMod/android_hardware_cm/blob/cm-11.0/power/Android.mk

**Comment by marduk191** [comment]
we can't merge this anyway because the time fix is included and it's broken at the moment.

**Comment by jied83** [comment]
need to test it again...something wrong....

**Comment by jied83** [comment]
temporary close

**Pull request closed without merging**
