### PR TITLE
Jellybean wifi fix 1/3

### PR DESCRIPTION
**Pull request by jied83**
commented hostapd in wifi.mk because it brake netd
modifed supplicants service to use android private socket and disabled strings for unix socket
disabled qcamerasrv it make noise in logcat

### CODE REVIEW

**Comment by jznomoney** [comment]
I have tested your changes and it works but only with one of my three routers.  I get this in my logcat
http://pastebin.com/7QzDevTU

**Comment by mifl** [comment]
Understanding that the repository: "vendor_pantech_presto", is not a dependency needed to compile our device, because it can be generated from the file: "proprietary-files.txt", we should adjust the changes to this file.

Propose the following changes, which affect the three repositories:
- http://pastebin.com/NH8CKDHt (Changed the link for some errors)

Greetings.

**Comment by jied83** [comment]
jznomoney 
could you show me /data/misc/wifi/wpa_suplicant.conf, but make sure that you delete passwd(they are not encrypted)
and logs from routers when pantech connecting, also what channels they are use, and is there are any mac filters?

**Comment by jied83** [comment]
ok, ill make correction.

**Comment by mifl** [comment]
Great job:
As a member of our team, you can include the merge when you want.
Thank you very much.
- Note: I'm too heavy to maintain order,  is because never lost hope that we do a merge the parent repository.

**Comment by jznomoney** [comment]
Ok so I figured out why it wouldn't connect to my routers.  The mac address in CM is different than the one in the stock ics.  I have them set to mac address filtering.

**Comment by jied83** [comment]
Could you provide Mac that assigned to your network interface?

**Comment by jznomoney** [comment]
00:0F:E4:3D:04:6D

**Comment by jied83** [comment]
hmm...strange 00:0F:E4 and A0:78:BA vendors ID belongs to PANTECH

A0-78-BA   (hex)        Pantech Co., Ltd.
A078BA     (base 16)        Pantech Co., Ltd.
                110-1 Ongjeong-Ri, Tongjin-Eup
                Gimpo-Si Gyounggi-Do 415-865
                KOREA, REPUBLIC OF
00-0F-E4   (hex)        Pantech Co.,Ltd
000FE4     (base 16)        Pantech Co.,Ltd
                Shinsong B/D 3F, 25-12,
                Yeouido-Dong,
                Youngdeungpo-GU Seoul 150-711
                KOREA, REPUBLIC OF
in the future we need to investigate why mac is changed, i think that our device was made in the likeness of device that sold in Korea, like SKY a760s, and software are same, so Pantech engineer make procedure(PACMAC in kernel) that change mac for Presto that sold in USA.

**Comment by jied83** [comment]
or this addresses is used for bluetooth....

**Comment by jznomoney** [comment]
My bluetooth mac address starts with A0 in stock.

**Comment by jied83** [comment]
ok, i have some idea, will check it later

**Pull request merged**
