### PR TITLE
EMMC brick bug,  audio alsa

### PR DESCRIPTION
**Pull request by mifl**
- Add: BOARD_SUPPRESS_EMMC_WIPE : = true
- Modified: Prebuilt Kernel from CyanogenMod repo
- Deleted: Kernel Configuration Files

### CODE REVIEW

**Comment by jied83** [comment]
we no need this 
+BOARD_USES_ALSA_AUDIO    := false

**Comment by mifl** [comment]
It is a mistake, I know after checking it had not changed the repository vendor.
Change the file again.

**Comment by mifl** [comment]
If you agree with the rest, I merge this Pull request

**Comment by jied83** [comment]
yep all ok

**Pull request merged**
