### PR TITLE
ril changes to PantechQualcommUiccRIL

### PR DESCRIPTION
**Pull request by stevotdo**
That should fix it.  Thank you for catching my error.

"Create ATT compatible RIL. This is the bare minimum I have found that gives me working data. It contains most of the information in "SamsungQualcommUiccRIL" but with anything pertaining to handling of sms removed. I have named it PantechQualcommUiccRIL in order to keep the naming convention already used for LGE, Samsung Devices."

### CODE REVIEW

**Comment by mifl** [comment]
As the file "PantechQualcommUiccRIL" is part of the framework, should have the structure of this, I think that we should place it in:
ril/telephony/java/com/android/internal/telephony/PantechQualcommUiccRIL.java

**Comment by stevotdo** [comment]
Will it be necessary to change the path to it in device.mk or will it still pick it up with the current information of "FRAMEWORKS_BASE_SUBDIRS += ../../$(LOCAL_PATH)/ril/"

It should be allright

**Comment by jied83** [comment]
i tested this commit and dont experiencing any problems on not ATT network.

**Comment by stevotdo** [comment]
Good,  I was curious if it would affect those of you not using an att sim.

**Comment by mifl** [comment]
I can not prove this, my device does not recognize the sim, but neither requested an unlock code.
But I think it's fine.

My problem is best discussed in the forum. I write the message there.

**Pull request merged**
