### PR TITLE
Pantech ril

### PR DESCRIPTION
**Pull request by stevotdo**
Create ATT compatible RIL.   This is the bare minimum I have found that gives me working data.  It contains most of the information in "SamsungQualcommUiccRIL" but with anything pertaining to handling of sms removed.  I have named it PantechQualcommUiccRIL in order to keep the naming convention already used for LGE, Samsung Devices.

### CODE REVIEW

**Comment by mifl** [comment]
Good job

**Comment by stevotdo** [comment]
Nevermind, I see what you mean.  I'll fix it.

**Comment by mifl** [comment]
To avoid problems, the best is that you delete the repo and make a new fork, then upload your changes again.
If you agree we close this request.

**Comment by stevotdo** [comment]
I completely agree. I will do it asap

**Pull request closed without merging**
