### PR TITLE
fix sdcard mounting; added proprietary files to file list; oncrpc permission for rild

### PR DESCRIPTION
**Pull request by jied83**
This Pull have dependencies:
- https://github.com/PantechDevTeam/android_device_pantech_qcom-common/pull/14
- https://github.com/PantechDevTeam/android_vendor_pantech_presto/pull/1
- https://github.com/PantechDevTeam/android_kernel_pantech_msm8660-common/pull/1

Thanks.

### CODE REVIEW

**Comment by jied83** [comment]
so, is anyone have tested this?

**Comment by bademux** [comment]
Let it go wild :)

**Comment by jied83** [comment]
i can add more commits here, to fix proximity sensor while call, camera wrapper, ril class fix

**Comment by jied83** [comment]
camera wrapper i will add later as standalone pull request

**Comment by jied83** [comment]
camera should work fine without it

**Comment by mifl** [comment]
Hi: To complete the commit: https://github.com/PantechDevteam/android_vendor_pantech_presto/commit/bacc3f973447fd78008fe1b5bef564674288387a
You need:

Remove this line in proprietary-files.tx:
https://github.com/PantechDevteam/android_device_pantech_presto/blob/cm-11.0/proprietary-files.txt#L10. 

And in rootdir/init.qcom.rc drop the function:

<pre>service atfwd /system/bin/ATFWD-daemon
    class late_start
    user system
    group system radio
    onrestart /system/bin/log -t RIL-ATFWD -p w "ATFWD daemon restarted"</pre>

**Comment by marduk191** [comment]
Too many commits to test. Patches should come first so that the build will compile. Not usable.

**Comment by marduk191** [comment]
Now there are duplicate commits in this pull request because we are using them in other repositories. presto_patchs.sh  is attempting to patch repositories that are already available and patched. This is fine because presto_patches.sh calls patches with incorrect paths. If we are going to use updated repositories, instead of patches, there is no longer a need for the duplicate patch script system including "presto_patchs.sh"  and the directory of "/device/pantech/presto/patchs". This is the best way to move forward, but this pull request needs to reflect those changes as well to avoid duplicate commits.

**Comment by mifl** [comment]
@marduk191: You are right, but with a single commit, this problem can be resolved: delete the patch folder. We must not waste time on things that have simple solutions, because the patches are an additional part

**Comment by jied83** [comment]
this commit fix patching mechanism
https://github.com/jied83/android_device_pantech_presto/commit/f26748444f0b371e9376264d5978c14b0a5881a5

currently this repo don't have commits that switchs from patchs to patched repository, so at this monent i dont see conflicts.

**Comment by marduk191** [comment]
The current state of this repository is unusable when a clean pull is made. without the additional repositories added it is not able to compile due to the patches we need. Adding the patches again, after it is usable, really makes no sense. I'm looking at it from the point of view of someone actually trying to use this repository to build this ROM. If it doesn't build, there is no reason to have the repository. The patching mechanism is broken in it's current state of simply running "presto_patches.sh -a" because the paths are incorrect. We can't use both methods. making the repository usable is not a waste of time.

**Comment by mifl** [comment]
@marduk191: You only need pick the commits made in the new common repos in your computer. We now know that all patches can be applied to the current code, which is why we must focus our efforts on solving the problems of the device, not in seeking new problems.

**Comment by marduk191** [comment]
Then this repository is not usable because it does not compile when someone tries to pull it and use the patch system. If it does not compile, the device work will not compile either. This is not a new problem.

**Comment by jied83** [comment]
whats your solution?

**Comment by marduk191** [comment]
either use the other repositories that were added, with the patches in the correct place, or modify the paths in the patch system to the correct ones lol. Either method would be perfectly fine.

**Comment by jied83** [comment]
but this https://github.com/jied83/android_device_pantech_presto/commit/f26748444f0b371e9376264d5978c14b0a5881a5

fixes paths, as said before
execute it from device/pantech/presto

**Comment by marduk191** [comment]
That is broken unless you replace the patch in the pull request, try it from the fresh repository pull.

**Comment by mifl** [comment]
I do not understand the problem, the repository is perfectly usable because it does not include these changes. If these changes work well, it is only necessary to include them in the correct order inside the repositories. And if we need to modify any of the commits, we speak these changes and concluded matter.
Please @jied83: if you have time, make a commit to delete the patches directory

**Comment by marduk191** [comment]
I'll do a fresh pull right now and see what has changed.

**Comment by marduk191** [comment]
The problem was already stated. We're doing the same thing twice lol

**Comment by jied83** [comment]
Ok, i deleted all patches and script

**Comment by jied83** [comment]
so i made last one commit, now i think everything must be ok.

**Comment by marduk191** [comment]
That last commit is already in our replacement repository. We can add the entire replacement to the local manifest without needing to commit it against the one we don't use.  https://gist.github.com/marduk191/abcb9c6e258f0c6e5aec

**Comment by jied83** [comment]
could you, please, specify commit in our replacement repository?

**Comment by marduk191** [comment]
nevermind, that's the second part to the patch lol.

**Comment by mifl** [comment]
@jied83:
The file: device/pantech/presto/include/BCameraParameters.h. I think that must be moved to: device/pantech/presto/camera/BCameraParameters.h. Because this is the specific header directory included in the mod.

**Comment by marduk191** [comment]
Build is fixed in the initial repositories, I loaded this entire pull request into a clean build. Should be ready to test in an hour if nothing breaks lol.

**Comment by marduk191** [comment]
You made changes after the build was started so it won't be correct. I'll have to build again and we also have no working recovery for 4.4. So that is what we'll have to fix before we can test. the old recoveries did not have selinux. Give it some time

**Comment by jied83** [comment]
Please write here when you will test these changes and i will merge

**Comment by marduk191** [comment]
I'll test them when they can compile and flash correctly lol. It could take a while figuring out the fstab changes unless one of you already did it once. The current repo doesn't boot or create a working recovery with your patches. I don't have a lot of time this week either.

**Comment by makx1998998** [comment]
kitkat flashed correctly in http://marduk191.blogspot.com/2013/05/pantech-burstp9070preso-twrp-recovery.html

**Comment by marduk191** [comment]
Flashing doesn't count, it has to boot lol. That recovery knows our partitions, so it will throw stuff around, it has no idea how to handle selinux in the recovery or kernel though. And kitkat doesn't know what to do yet either. You must have built from a repo that is not here. This is a patch against the PDT repos with selinux enabled. If you have patches to fix this, please send them so we can move on lol.

**Comment by jied83** [comment]
selinux currently disabled in PDT's repo
and it boots
if your build don't boot, please, provide logcat and dmesg

**Comment by marduk191** [comment]
build it and see, I built a manifest, you just init cm11, add it to the local_manifest folder, sync. replace the device repo with yours, and compile. I left it on my gist from github. if it's not broken then I am getting wrong files and can't test anymore. I built clean and direct from the PDT repo. if it works then something on my machine won't work.

**Comment by mifl** [comment]
@marduk191: "I built clean and direct from the PDT repo."
But over the PDT repos. What patches have you applied?. I suppose you have applied all patches, from all pull requests, over the clean repositories. No?
Change in your manifest, all repos affected by pulls, by the Vald repos.

**Comment by marduk191** [comment]
ok, there were pull requests linked to this in other repos, I'll get this sorted and do my best to have everything merged and moving forward by morning.

**Comment by marduk191** [comment]
@mifl, yes, we established that

**Comment by marduk191** [comment]
The build server now greps from the group dashboard so that this isn't a problem again lmao

**Comment by marduk191** [comment]
I had to wrestle with the configs, it seems cm.mk isn't being called? all these patches work and can merge whenever you guys agree. the two associated with it can be as well. _edit_ didn't test the kernel patch. It looks good though.

**Pull request merged**
