### PR TITLE
Audio fix

### PR DESCRIPTION
**Pull request by jied83**
Change-Id: I01d719f6024eae348f3c3b20abeaddfa7575e526

### CODE REVIEW

**Comment by mifl** [comment]
- media/media_codecs.xml. Ok.
- media/media_profiles.xml. OK

BoardConfig.mk:

Check this please:
- https://github.com/CyanogenMod/android_hardware_qcom_audio/blob/jellybean/Android.mk

Audio must be define:
    ifneq ($(TARGET_PROVIDES_LIBAUDIO),true)
    ifneq ($(BOARD_USES_AUDIO_LEGACY),true)
    ifeq ($(BOARD_USES_QCOM_HARDWARE),true)
................................
    ifeq ($(TARGET_BOARD_PLATFORM),msm8660)
    include $(AUDIO_HW_ROOT)/msm8660/Android.mk
    include $(AUDIO_HW_ROOT)/mm-audio/Android.mk
    endif
................................

Greetings.

**Comment by jied83** [comment]
yep, if  BOARD_USES_QCOM_HARDWARE = true (defined in boardconfig)
 if BOARD_USES_AUDIO_LEGACY ,TARGET_PROVIDES_LIBAUDIO  not true (not defined)

and if  TARGET_BOARD_PLATFORM msm8660 true (defined in boardconfig )

so its ok

**Comment by mifl** [comment]
For my ok this:

#Audio
BOARD_USES_AUDIO_LEGACY := false
TARGET_PROVIDES_LIBAUDIO := false

I think it's better to have a section dedicated to the audio in the file, to keep the file structure.

Greetings.

**Comment by jied83** [comment]
agree, its more logical

**Pull request merged**
