### PR TITLE
Add audio_policy, del llvm-select.mk, ...

### PR DESCRIPTION
**Pull request by mifl**
Change-Id: I6377cf0c30792386a7eb735e73060e079732edba

In device.mk:
    - Change in the form of call gps.conf.
    - Simplified kernel prebuilt integration.
    - Imported "audio_policy.conf" from lg p930
    - Delete the duplicate # misc PRODUCT_PROPERTY_OVERRIDES.

In qcom-common.mk:
    - Only includes "PRODUCT_PACKAGES", the rest of code is moves to device.mk
    - Restructuring PRODUCT_PACKAGES, removing unnecessary lines, example: 
        (PRODUCT_PACKAGES += \
        libangle
        to
        PRODUCT_PACKAGES += libangle)
    - Deleted file "llvm-select.mk" and code to included it.
    - Commented the line #PRODUCT_PACKAGES += libQcomUI now is libqdutils. Sorry, I forgot to remove the line in "proprietary-files.txt"

In setup-makefiles.sh
    - Delete obj/lib/libqc-opt.so, not necessary yet. Affect the repository vendor, if approved the change, automatically switch there.

### CODE REVIEW

**Comment by jied83** [comment]
all things seems to be ok, but im not sure about audio_policy.conf.
while build we get it from /hardware/qcom/audio/msm8660

**Comment by mifl** [comment]
Well, now it does not create the file "audio_policy.conf" and force them to be copied.

**Comment by jied83** [comment]
Update mount block - all ok, internal flash mounted in android

**Comment by stevotdo** [comment]
Looks good

**Pull request merged**
