### PR TITLE
Jellybean

### PR DESCRIPTION
**Pull request by jied83**

### CODE REVIEW

**Comment by mifl** [comment]
You can check if it works well doing:
/overlay/frameworks/base/services/java/com/android/server/PowerManagerService.java
or using:
FRAMEWORKS_BASE_SUBDIRS += ../../$(LOCAL_PATH)/services/

**Comment by jied83** [comment]
oh...i will check tommorow, thank you for advice

**Comment by mifl** [comment]
To avoid saturating in feedback, in our repository "GitHub", has created a forum section that allows us to discuss the changes. Can only be accessed by developers and administrators.
- http://www.devsnest.com/phpbb/viewtopic.php?f=127&t=102

**Comment by jied83** [comment]
ok, to apply all patchs need to execute apply_patchs.sh one time
to apply one of patchs need to go to cm_dir and patch -p0 -i device/pantech/presto/patchs/_patch_

also fixed move to sd function

**Comment by jied83** [comment]
guys test it plz, im not sure that all things correct

**Pull request closed without merging**
