### PR TITLE
Jellybean

### PR DESCRIPTION
**Pull request by jied83**
Audio/ril fix

to compile need to copy wifi/wifi.c to hardware/libhardware_legacy/wifi/
or may be anyone will create correct make script?

### CODE REVIEW

**Comment by mifl** [comment]
Notes:
- uevent.rc, already defined in rootdir/Android.mk.
- Need add new vendor files to proprietary-files.txt
- service skytestserver duplicated (rootdir/etc/init.qcom.rc and rootdir/etc/init.presto.rc). For me it is better stay in init.presto.rc.

Greetings.

**Comment by stevotdo** [comment]
proprietary-files.txt needs to be updated to reflect new vendor files

**Comment by jied83** [comment]
okey guys, i will update today skytestserver and prop file, but in my case ueventd.rc is not copied.

**Comment by stevotdo** [comment]
That's because ueventd.rc is not referenced in qcom-common.mk under #INIT

**Comment by jied83** [comment]
because it in device.mk

PRODUCT_PACKAGES += \
    init.presto.rc \
    ueventd.rc

but it dont work

**Comment by stevotdo** [comment]
I could be wrong.  Late night is frying my brain.

**Comment by jied83** [comment]
Updated. + turned off on screen keys and expanded desktop

**Comment by mifl** [comment]
For me ok.

**Comment by stevotdo** [comment]
Good

**Pull request merged**
